<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Assignments.aspx.cs" Inherits="AssignmentSystem.Assignments1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Tandlæge Net</title>
    <link href="Content/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" />
    <link href="Content/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="Content/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="Content/Form-Signin.css" rel="stylesheet" />
</head>
<body style="background-color: lightgrey; padding: 0 90px;">
    <br />
    <br />
    <form id="form1" runat="server" class="container">
        <div class="jumbotron">
            <h1>Tand Klinik Opgaver</h1>
            <asp:Label runat="server" ID="lbl_Account" CssClass="label label-default">Test</asp:Label>
            <br />
            <div>

                <asp:GridView ID="OpgaveView" runat="server" AutoGenerateColumns="False" DataKeyNames="AktivitetId" DataSourceID="TandDBSource" GridLines="None" CssClass="table table-striped table-hover" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                    <Columns>
                        <asp:BoundField DataField="AktivitetId" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="AktivitetId" />
                        <asp:BoundField DataField="AktivitetTitel" HeaderText="Titel" SortExpression="AktivitetTitel" />
                        <asp:BoundField DataField="AktivitetBeskrivelse" HeaderText="Beskrivelse" SortExpression="AktivitetBeskrivelse" />
                        <asp:BoundField DataField="AktivitetStatus" HeaderText="Status" SortExpression="AktivitetStatus" />
                        <asp:BoundField DataField="AktivitetFrist" HeaderText="Frist" SortExpression="AktivitetFrist" />
                    </Columns>
                </asp:GridView>

                <asp:SqlDataSource ID="TandDBSource" runat="server" ConnectionString="<%$ ConnectionStrings:TandConString %>" SelectCommand="SELECT [AktivitetId], [AktivitetTitel], [AktivitetBeskrivelse], [AktivitetStatus], [AktivitetFrist] FROM [Aktiviteter]" DeleteCommand="DELETE FROM [Aktiviteter] WHERE [AktivitetId] = @original_AktivitetId AND [AktivitetTitel] = @original_AktivitetTitel AND [AktivitetBeskrivelse] = @original_AktivitetBeskrivelse AND [AktivitetStatus] = @original_AktivitetStatus AND [AktivitetFrist] = @original_AktivitetFrist" ConflictDetection="CompareAllValues" InsertCommand="INSERT INTO [Aktiviteter] ([AktivitetTitel], [AktivitetBeskrivelse], [AktivitetStatus], [AktivitetFrist]) VALUES (@AktivitetTitel, @AktivitetBeskrivelse, @AktivitetStatus, @AktivitetFrist)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [Aktiviteter] SET [AktivitetTitel] = @AktivitetTitel, [AktivitetBeskrivelse] = @AktivitetBeskrivelse, [AktivitetStatus] = @AktivitetStatus, [AktivitetFrist] = @AktivitetFrist WHERE [AktivitetId] = @original_AktivitetId AND [AktivitetTitel] = @original_AktivitetTitel AND [AktivitetBeskrivelse] = @original_AktivitetBeskrivelse AND [AktivitetStatus] = @original_AktivitetStatus AND [AktivitetFrist] = @original_AktivitetFrist">
                    <DeleteParameters>
                        <asp:Parameter Name="original_AktivitetId" Type="Int32" />
                        <asp:Parameter Name="original_AktivitetTitel" Type="String" />
                        <asp:Parameter Name="original_AktivitetBeskrivelse" Type="String" />
                        <asp:Parameter Name="original_AktivitetStatus" Type="String" />
                        <asp:Parameter DbType="Date" Name="original_AktivitetFrist" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="AktivitetTitel" Type="String" />
                        <asp:Parameter Name="AktivitetBeskrivelse" Type="String" />
                        <asp:Parameter Name="AktivitetStatus" Type="String" />
                        <asp:Parameter DbType="Date" Name="AktivitetFrist" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="AktivitetTitel" Type="String" />
                        <asp:Parameter Name="AktivitetBeskrivelse" Type="String" />
                        <asp:Parameter Name="AktivitetStatus" Type="String" />
                        <asp:Parameter DbType="Date" Name="AktivitetFrist" />
                        <asp:Parameter Name="original_AktivitetId" Type="Int32" />
                        <asp:Parameter Name="original_AktivitetTitel" Type="String" />
                        <asp:Parameter Name="original_AktivitetBeskrivelse" Type="String" />
                        <asp:Parameter Name="original_AktivitetStatus" Type="String" />
                        <asp:Parameter DbType="Date" Name="original_AktivitetFrist" />
                    </UpdateParameters>
                </asp:SqlDataSource>

                <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>

                <br />
                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Modal Test</button>
                <asp:Button runat="server" ID="btn_Logout" Text="Logout" CssClass="btn btn-info btn-lg" OnClick="btn_Logout_OnClick" />
            </div>
        </div>
    </form>
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Modal Header</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>





    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>
