using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;

namespace AssignmentSystem
{
    public partial class Assignments1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            Response.Cache.SetNoStore(); //sørger for at en aspx side ikke bliver cached

            if (Session["LoggedIn"] == null)
            {
                Response.Redirect("Login-Page.aspx"); // Hvis sessionen er null, så bliver man smidt tilbage til login siden
            }
            else
            {
                lbl_Account.Text = Session["Account"].ToString(); // Viser brugerens information(display name & Email adresse)
            }

            if (Convert.ToInt32(Session["Authority"]) == 2)
            {
                OpgaveView.AutoGenerateDeleteButton = true;
                OpgaveView.AutoGenerateEditButton = true;
                div_tilføj.Visible = true;
            }else
            {
                OpgaveView.AutoGenerateEditButton = false;
                OpgaveView.AutoGenerateDeleteButton = false;
                div_tilføj.Visible = false;

            }
            lbl_Result.Text = string.Empty;


        }

        protected void btn_Logout_OnClick(object sender, EventArgs e)
        {
            Session.Clear(); // fjerner alle keys og session values fra den nuværrende session
            Session.Abandon(); // Anullere den nuværende session
            Response.Redirect("Login-Page.aspx"); // sender brugeren tilbage til login siden
        }
        protected void btn_Insert_OnClick(object sender, EventArgs e)
        {
            Assignment insertAssignment = new Assignment(tb_Titel.Text, tb_Beskrivelse.Text, tb_ansvarlig.Text, DateTime.Now);

            string result = insertAssignment.InsertToTable();

            if (result == "success")
            {
                ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "Success" + "');", true);
                OpgaveView.DataBind();
            }
            else
            {
                lbl_Result.Text = "Der skete en fejl.";
            }
        }
    }
}